# -*- coding: utf-8 -*-
"""
Inference script for RDcomm on OpenCOOD.

This script evaluates PointPillar-RDcomm under the full communication-efficient
inference pipeline:

    BEV feature
      -> confidence selection Mc
      -> layered VQ indices Dbase/Dres
      -> task entropy coding bit accounting
      -> MI selection MMI
      -> smoothing UNet
      -> RDcomm fusion
      -> detection head
      -> OpenCOOD post-processing / AP evaluation

Recommended command:

    python opencood/tools/inference_rdcomm.py \
      --hypes_yaml opencood/hypes_yaml/rdcomm/point_pillar_rdcomm_opv2v_infer.yaml \
      --checkpoint path/to/stage3/net_epochXX.pth \
      --huffman_table path/to/stage2/huffman_table.pth \
      --tau_c 0.005 \
      --tau_mi 0.7 \
      --output_dir opencood/logs/rdcomm_eval/opv2v_tau0005

Batch sweep is handled by tools/rdcomm_eval_bandwidth.py.
"""

import argparse
import copy
import csv
import json
import os
import random
import time
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple, Union

import numpy as np
import torch
from torch.utils.data import DataLoader


from opencood.hypes_yaml import yaml_utils
from opencood.data_utils.datasets import build_dataset
from opencood.tools import train_utils

try:
    from opencood.utils import eval_utils
except Exception:
    eval_utils = None

from opencood.utils.rdcomm_checkpoint_utils import (
    load_state_dict_flexible,
    configure_inference_mode,
)


# -------------------------------------------------------------------------
# Args
# -------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="RDcomm inference / AP-communication evaluation."
    )

    parser.add_argument(
        "--hypes_yaml",
        "-y",
        type=str,
        required=True,
        help="Path to RDcomm inference yaml.",
    )

    parser.add_argument(
        "--checkpoint",
        "--ckpt",
        type=str,
        required=True,
        help="Path to RDcomm checkpoint or checkpoint directory.",
    )

    parser.add_argument(
        "--huffman_table",
        type=str,
        default="",
        help=(
            "Path to huffman_table.pth generated by rdcomm_build_huffman.py. "
            "If empty, fixed-length coding is used by the model."
        ),
    )

    parser.add_argument(
        "--output_dir",
        "-o",
        type=str,
        default="",
        help="Directory for inference results. If empty, created next to checkpoint.",
    )

    parser.add_argument(
        "--rdcomm_stage",
        type=str,
        default="infer",
        choices=["infer", "inference", "stage2_vq", "stage3_mi"],
        help="Model stage. Default is infer.",
    )

    parser.add_argument(
        "--tau_c",
        type=float,
        default=None,
        help="Override confidence threshold tau_c.",
    )

    parser.add_argument(
        "--tau_mi",
        type=float,
        default=None,
        help="Override MI threshold tau_mi.",
    )

    parser.add_argument(
        "--batch_size",
        type=int,
        default=None,
        help="Override test batch size.",
    )

    parser.add_argument(
        "--num_workers",
        type=int,
        default=None,
        help="Override dataloader num_workers.",
    )

    parser.add_argument(
        "--max_batches",
        type=int,
        default=-1,
        help="Maximum number of batches. Negative means all.",
    )

    parser.add_argument(
        "--ap_thresholds",
        type=str,
        default="0.3,0.5,0.7",
        help="IoU thresholds for AP evaluation, comma-separated.",
    )

    parser.add_argument(
        "--global_sort_detections",
        action="store_true",
        help="Use global sorting in OpenCOOD final AP evaluation if supported.",
    )

    parser.add_argument(
        "--strict_load",
        action="store_true",
        help="Use strict checkpoint loading.",
    )

    parser.add_argument(
        "--no_ignore_shape_mismatch",
        action="store_true",
        help="Do not skip shape-mismatched checkpoint tensors.",
    )

    parser.add_argument(
        "--data_parallel",
        action="store_true",
        help="Use DataParallel when multiple GPUs are available.",
    )

    parser.add_argument(
        "--no_cuda",
        action="store_true",
        help="Force CPU inference.",
    )

    parser.add_argument(
        "--save_predictions",
        action="store_true",
        help="Save raw prediction / GT tensors as torch files.",
    )

    parser.add_argument(
        "--save_per_sample_csv",
        action="store_true",
        help="Save per-batch communication statistics to CSV.",
    )

    parser.add_argument(
        "--debug",
        action="store_true",
        help="Print debug information.",
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=0,
        help="Random seed. Negative disables fixed seed.",
    )

    return parser.parse_args()


# -------------------------------------------------------------------------
# General helpers
# -------------------------------------------------------------------------


def set_random_seed(seed: int) -> None:
    if seed is None or int(seed) < 0:
        return

    seed = int(seed)

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


def get_device(no_cuda: bool = False) -> torch.device:
    if no_cuda:
        return torch.device("cpu")
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def get_core_model(model: torch.nn.Module) -> torch.nn.Module:
    return model.module if hasattr(model, "module") else model


def recursive_to_device(data: Any, device: torch.device) -> Any:
    if isinstance(data, torch.Tensor):
        return data.to(device)

    if isinstance(data, Mapping):
        return {k: recursive_to_device(v, device) for k, v in data.items()}

    if isinstance(data, list):
        return [recursive_to_device(v, device) for v in data]

    if isinstance(data, tuple):
        return tuple(recursive_to_device(v, device) for v in data)

    return data


def to_device(data: Any, device: torch.device) -> Any:
    if hasattr(train_utils, "to_device"):
        return train_utils.to_device(data, device)
    return recursive_to_device(data, device)


def get_nested_dict(
    data: Mapping[str, Any],
    keys: Sequence[str],
    default: Any = None,
) -> Any:
    cur = data

    for key in keys:
        if not isinstance(cur, Mapping) or key not in cur:
            return default
        cur = cur[key]

    return cur


def set_nested_dict(
    data: Dict[str, Any],
    keys: Sequence[str],
    value: Any,
) -> None:
    cur = data

    for key in keys[:-1]:
        if key not in cur or not isinstance(cur[key], Mapping):
            cur[key] = {}
        cur = cur[key]

    cur[keys[-1]] = value


def ensure_dir(path: str) -> str:
    os.makedirs(path, exist_ok=True)
    return path


def parse_thresholds(value: str) -> List[float]:
    return [float(v.strip()) for v in value.replace(";", ",").split(",") if v.strip()]


def tensor_to_cpu(value: Any) -> Any:
    if isinstance(value, torch.Tensor):
        return value.detach().cpu()

    if isinstance(value, Mapping):
        return {k: tensor_to_cpu(v) for k, v in value.items()}

    if isinstance(value, list):
        return [tensor_to_cpu(v) for v in value]

    if isinstance(value, tuple):
        return tuple(tensor_to_cpu(v) for v in value)

    return value


def to_float(value: Any, default: float = 0.0) -> float:
    if value is None:
        return float(default)

    if isinstance(value, torch.Tensor):
        if value.numel() == 0:
            return float(default)
        return float(value.detach().float().mean().cpu().item())

    try:
        return float(value)
    except Exception:
        return float(default)


def resolve_output_dir(args: argparse.Namespace) -> str:
    if args.output_dir:
        return ensure_dir(args.output_dir)

    if os.path.isdir(args.checkpoint):
        root = args.checkpoint
    else:
        root = os.path.dirname(os.path.abspath(args.checkpoint))

    tau_c_str = "none" if args.tau_c is None else f"{args.tau_c:g}".replace(".", "p")
    tau_mi_str = "none" if args.tau_mi is None else f"{args.tau_mi:g}".replace(".", "p")

    output_dir = os.path.join(root, f"rdcomm_infer_tauc_{tau_c_str}_taumi_{tau_mi_str}")
    return ensure_dir(output_dir)


def load_yaml(args: argparse.Namespace) -> Dict[str, Any]:
    try:
        hypes = yaml_utils.load_yaml(args.hypes_yaml, args)
    except TypeError:
        hypes = yaml_utils.load_yaml(args.hypes_yaml)

    return copy.deepcopy(hypes)


def update_hypes_for_inference(
    hypes: Dict[str, Any],
    args: argparse.Namespace,
) -> Dict[str, Any]:
    stage = str(args.rdcomm_stage).lower()
    if stage == "inference":
        stage = "infer"

    set_nested_dict(hypes, ("model", "args", "rdcomm_stage"), stage)
    set_nested_dict(hypes, ("model", "args", "rdcomm", "stage"), stage)

    if args.tau_c is not None:
        set_nested_dict(hypes, ("model", "args", "tau_c"), float(args.tau_c))
        set_nested_dict(hypes, ("model", "args", "rdcomm", "tau_c"), float(args.tau_c))
        set_nested_dict(
            hypes,
            ("model", "args", "rdcomm", "confidence", "tau_c"),
            float(args.tau_c),
        )

    if args.tau_mi is not None:
        set_nested_dict(hypes, ("model", "args", "tau_mi"), float(args.tau_mi))
        set_nested_dict(hypes, ("model", "args", "rdcomm", "tau_mi"), float(args.tau_mi))
        set_nested_dict(
            hypes,
            ("model", "args", "rdcomm", "mi", "tau_mi"),
            float(args.tau_mi),
        )

    return hypes


def get_train_params(hypes: Mapping[str, Any]) -> Mapping[str, Any]:
    return hypes.get("train_params", hypes.get("train", {}))


def get_batch_size(args: argparse.Namespace, hypes: Mapping[str, Any]) -> int:
    if args.batch_size is not None:
        return int(args.batch_size)

    train_params = get_train_params(hypes)
    return int(train_params.get("test_batch_size", train_params.get("val_batch_size", 1)))


def get_num_workers(args: argparse.Namespace, hypes: Mapping[str, Any]) -> int:
    if args.num_workers is not None:
        return int(args.num_workers)

    train_params = get_train_params(hypes)
    return int(train_params.get("num_workers", 4))


def get_model_input(batch_data: Mapping[str, Any], stage: str) -> Mapping[str, Any]:
    if "ego" in batch_data and isinstance(batch_data["ego"], Mapping):
        model_input = batch_data["ego"]
    else:
        model_input = batch_data

    if isinstance(model_input, dict):
        model_input["rdcomm_stage"] = stage

    return model_input


# -------------------------------------------------------------------------
# Builders
# -------------------------------------------------------------------------


def build_test_loader(
    args: argparse.Namespace,
    hypes: Mapping[str, Any],
) -> Tuple[Any, DataLoader]:
    dataset = build_dataset(hypes, visualize=False, train=False)

    if hasattr(dataset, "collate_batch_test"):
        collate_fn = dataset.collate_batch_test
    elif hasattr(dataset, "collate_batch_train"):
        collate_fn = dataset.collate_batch_train
    else:
        raise AttributeError(
            "Dataset must provide collate_batch_test or collate_batch_train."
        )

    loader = DataLoader(
        dataset,
        batch_size=get_batch_size(args, hypes),
        shuffle=False,
        num_workers=get_num_workers(args, hypes),
        collate_fn=collate_fn,
        pin_memory=torch.cuda.is_available() and not args.no_cuda,
        drop_last=False,
    )

    return dataset, loader


def create_model(hypes: Mapping[str, Any]) -> torch.nn.Module:
    try:
        return train_utils.create_model(hypes)
    except Exception as exc:
        try:
            from opencood.models.point_pillar_rdcomm import PointPillarRdcomm
            return PointPillarRdcomm(hypes["model"]["args"])
        except Exception:
            raise exc


def set_model_stage(model: torch.nn.Module, stage: str) -> None:
    core = get_core_model(model)

    if hasattr(core, "set_rdcomm_stage"):
        core.set_rdcomm_stage(stage)
    elif hasattr(core, "rdcomm_stage"):
        core.rdcomm_stage = stage


def set_model_thresholds(
    model: torch.nn.Module,
    tau_c: Optional[float],
    tau_mi: Optional[float],
) -> None:
    core = get_core_model(model)

    if hasattr(core, "set_thresholds"):
        core.set_thresholds(tau_c=tau_c, tau_mi=tau_mi)
        return

    if tau_c is not None and hasattr(core, "tau_c"):
        core.tau_c = float(tau_c)

    if tau_mi is not None and hasattr(core, "tau_mi"):
        core.tau_mi = float(tau_mi)


def load_model_checkpoint(
    model: torch.nn.Module,
    checkpoint: str,
    device: torch.device,
    strict: bool,
    ignore_shape_mismatch: bool,
) -> Dict[str, Any]:
    core = get_core_model(model)

    return load_state_dict_flexible(
        model=core,
        checkpoint_or_state_dict=checkpoint,
        map_location=device,
        strict=bool(strict),
        ignore_shape_mismatch=bool(ignore_shape_mismatch),
        verbose=True,
    )


def load_huffman_table_if_needed(
    model: torch.nn.Module,
    table_path: str,
) -> None:
    if not table_path:
        print("[RDcomm infer] no huffman_table provided; model will use current/fixed code lengths.")
        return

    core = get_core_model(model)

    if hasattr(core, "load_entropy_table"):
        core.load_entropy_table(table_path, strict_size=True)
        print(f"[RDcomm infer] huffman table loaded: {table_path}")
        return

    if hasattr(core, "entropy_coder"):
        core.entropy_coder.load_table(table_path, strict_size=True)
        print(f"[RDcomm infer] huffman table loaded: {table_path}")
        return

    raise AttributeError(
        "Model has no load_entropy_table() or entropy_coder. "
        "Please check point_pillar_rdcomm.py."
    )


# -------------------------------------------------------------------------
# Post-processing / eval helpers
# -------------------------------------------------------------------------


def post_process_batch(
    dataset: Any,
    batch_data: Mapping[str, Any],
    output_dict: Mapping[str, Any],
) -> Tuple[Optional[torch.Tensor], Optional[torch.Tensor], Optional[torch.Tensor]]:
    """
    Run OpenCOOD post_processor.post_process.

    Returns:
        pred_box_tensor, pred_score, gt_box_tensor
    """
    if not hasattr(dataset, "post_processor"):
        raise AttributeError("Dataset does not have post_processor.")

    post_processor = dataset.post_processor

    post_input = batch_data["ego"] if "ego" in batch_data else batch_data

    try:
        return post_processor.post_process(post_input, output_dict)
    except Exception:
        # Some versions expect the full batch_data.
        return post_processor.post_process(batch_data, output_dict)


def init_result_stat(thresholds: Sequence[float]) -> Dict[float, Dict[str, Any]]:
    return {
        float(th): {
            "tp": [],
            "fp": [],
            "gt": 0,
            "score": [],
        }
        for th in thresholds
    }


def update_result_stat(
    result_stat: Dict[float, Dict[str, Any]],
    pred_box_tensor: Optional[torch.Tensor],
    pred_score: Optional[torch.Tensor],
    gt_box_tensor: Optional[torch.Tensor],
    thresholds: Sequence[float],
) -> None:
    """
    Update OpenCOOD-style result_stat.
    """
    if eval_utils is not None and hasattr(eval_utils, "caluclate_tp_fp"):
        for thresh in thresholds:
            eval_utils.caluclate_tp_fp(
                pred_box_tensor,
                pred_score,
                gt_box_tensor,
                result_stat,
                float(thresh),
            )
        return

    if eval_utils is not None and hasattr(eval_utils, "calculate_tp_fp"):
        for thresh in thresholds:
            eval_utils.calculate_tp_fp(
                pred_box_tensor,
                pred_score,
                gt_box_tensor,
                result_stat,
                float(thresh),
            )
        return

    raise ImportError(
        "Cannot find eval_utils.caluclate_tp_fp / calculate_tp_fp. "
        "Please use your OpenCOOD eval_utils or add the function."
    )


def calculate_ap_from_stat_single(stat: Mapping[str, Any]) -> float:
    """
    Fallback AP calculation from result_stat[threshold].
    """
    tp = np.array(stat.get("tp", []), dtype=np.float32)
    fp = np.array(stat.get("fp", []), dtype=np.float32)
    scores = np.array(stat.get("score", []), dtype=np.float32)
    gt = int(stat.get("gt", 0))

    if gt <= 0 or tp.size == 0:
        return 0.0

    if scores.size == tp.size:
        order = np.argsort(-scores)
        tp = tp[order]
        fp = fp[order]

    tp_cum = np.cumsum(tp)
    fp_cum = np.cumsum(fp)

    recalls = tp_cum / max(float(gt), 1.0)
    precisions = tp_cum / np.maximum(tp_cum + fp_cum, 1e-12)

    # VOC-style integral AP.
    mrec = np.concatenate(([0.0], recalls, [1.0]))
    mpre = np.concatenate(([0.0], precisions, [0.0]))

    for i in range(mpre.size - 1, 0, -1):
        mpre[i - 1] = np.maximum(mpre[i - 1], mpre[i])

    changing_points = np.where(mrec[1:] != mrec[:-1])[0]
    ap = np.sum((mrec[changing_points + 1] - mrec[changing_points]) * mpre[changing_points + 1])

    return float(ap)


def final_eval_results(
    result_stat: Dict[float, Dict[str, Any]],
    output_dir: str,
    global_sort_detections: bool = False,
) -> Dict[str, float]:
    """
    Use OpenCOOD final eval when available, otherwise fallback.
    """
    if eval_utils is not None and hasattr(eval_utils, "eval_final_results"):
        try:
            ret = eval_utils.eval_final_results(
                result_stat,
                output_dir,
                global_sort_detections=global_sort_detections,
            )
        except TypeError:
            try:
                ret = eval_utils.eval_final_results(result_stat, output_dir)
            except TypeError:
                ret = eval_utils.eval_final_results(result_stat)

        if isinstance(ret, Mapping):
            return {str(k): float(v) for k, v in ret.items() if isinstance(v, (int, float))}

        if isinstance(ret, tuple):
            out: Dict[str, float] = {}
            sorted_thresholds = sorted(result_stat.keys())
            for idx, value in enumerate(ret):
                if idx < len(sorted_thresholds):
                    out[f"AP{int(sorted_thresholds[idx] * 100)}"] = float(value)
                else:
                    out[f"AP_{idx}"] = float(value)
            return out

    ap_dict = {}
    for thresh, stat in result_stat.items():
        ap_dict[f"AP{int(float(thresh) * 100)}"] = calculate_ap_from_stat_single(stat)

    return ap_dict


# -------------------------------------------------------------------------
# Communication stats
# -------------------------------------------------------------------------


def extract_comm_stats(output_dict: Mapping[str, Any]) -> Dict[str, float]:
    """
    Extract communication stats from model output.
    """
    stats: Dict[str, float] = {}

    comm_stats = output_dict.get("comm_stats", None)

    if isinstance(comm_stats, Mapping):
        for key, value in comm_stats.items():
            if isinstance(value, (int, float, torch.Tensor)):
                stats[str(key)] = to_float(value)

    for key in ("comm_bits", "comm_KB", "comm_MB"):
        if key in output_dict:
            stats[key] = to_float(output_dict[key])

    # Ensure canonical fields exist.
    if "total_bits" not in stats and "comm_bits" in stats:
        stats["total_bits"] = stats["comm_bits"]

    if "total_KB" not in stats and "comm_KB" in stats:
        stats["total_KB"] = stats["comm_KB"]

    if "total_MB" not in stats and "comm_MB" in stats:
        stats["total_MB"] = stats["comm_MB"]

    return stats


def aggregate_comm_stats(stats_list: Sequence[Mapping[str, float]]) -> Dict[str, float]:
    """
    Aggregate communication stats over all batches.
    """
    if len(stats_list) == 0:
        return {
            "total_bits": 0.0,
            "total_KB": 0.0,
            "total_MB": 0.0,
            "avg_bits_per_batch": 0.0,
            "avg_KB_per_batch": 0.0,
            "avg_MB_per_batch": 0.0,
            "avg_final_selected_ratio": 0.0,
            "avg_confidence_selected_ratio": 0.0,
            "avg_mi_selected_ratio_within_confidence": 0.0,
            "num_batches": 0.0,
        }

    sum_keys = (
        "total_bits",
        "total_bytes",
        "total_KB",
        "total_MB",
        "selected_message_bits",
        "selected_message_KB",
        "abstract_bits",
        "abstract_KB",
        "num_messages",
    )

    mean_keys = (
        "final_selected_ratio",
        "confidence_selected_ratio",
        "mi_selected_ratio_within_confidence",
    )

    out: Dict[str, float] = {}

    for key in sum_keys:
        out[key] = float(sum(float(s.get(key, 0.0)) for s in stats_list))

    n = max(len(stats_list), 1)

    out["avg_bits_per_batch"] = out.get("total_bits", 0.0) / n
    out["avg_KB_per_batch"] = out.get("total_KB", 0.0) / n
    out["avg_MB_per_batch"] = out.get("total_MB", 0.0) / n

    for key in mean_keys:
        out[f"avg_{key}"] = float(sum(float(s.get(key, 0.0)) for s in stats_list)) / n

    out["num_batches"] = float(len(stats_list))
    return out


def write_comm_csv(
    rows: Sequence[Mapping[str, Any]],
    path: str,
) -> str:
    if len(rows) == 0:
        return path

    fieldnames = sorted(set(k for row in rows for k in row.keys()))

    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)

    return path


# -------------------------------------------------------------------------
# Save helpers
# -------------------------------------------------------------------------


def save_json(data: Mapping[str, Any], path: str) -> str:
    def convert(obj: Any) -> Any:
        if isinstance(obj, torch.Tensor):
            if obj.numel() == 1:
                return obj.detach().cpu().item()
            return obj.detach().cpu().tolist()

        if isinstance(obj, np.ndarray):
            return obj.tolist()

        if isinstance(obj, Mapping):
            return {str(k): convert(v) for k, v in obj.items()}

        if isinstance(obj, list):
            return [convert(v) for v in obj]

        if isinstance(obj, tuple):
            return [convert(v) for v in obj]

        return obj

    parent = os.path.dirname(os.path.abspath(path))
    if parent:
        os.makedirs(parent, exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        json.dump(convert(data), f, indent=2, ensure_ascii=False)

    return path


def save_prediction_item(
    output_dir: str,
    batch_idx: int,
    pred_box_tensor: Optional[torch.Tensor],
    pred_score: Optional[torch.Tensor],
    gt_box_tensor: Optional[torch.Tensor],
    output_dict: Mapping[str, Any],
) -> None:
    pred_dir = os.path.join(output_dir, "predictions")
    os.makedirs(pred_dir, exist_ok=True)

    item = {
        "pred_box_tensor": tensor_to_cpu(pred_box_tensor),
        "pred_score": tensor_to_cpu(pred_score),
        "gt_box_tensor": tensor_to_cpu(gt_box_tensor),
        "comm_stats": tensor_to_cpu(output_dict.get("comm_stats", {})),
    }

    torch.save(item, os.path.join(pred_dir, f"batch_{batch_idx:06d}.pth"))


# -------------------------------------------------------------------------
# Main inference loop
# -------------------------------------------------------------------------


@torch.no_grad()
def run_inference(
    model: torch.nn.Module,
    dataset: Any,
    loader: DataLoader,
    device: torch.device,
    args: argparse.Namespace,
    output_dir: str,
) -> Dict[str, Any]:
    stage = str(args.rdcomm_stage).lower()
    if stage == "inference":
        stage = "infer"

    thresholds = parse_thresholds(args.ap_thresholds)
    result_stat = init_result_stat(thresholds)

    model.eval()

    comm_rows: List[Dict[str, Any]] = []
    comm_stats_list: List[Dict[str, float]] = []

    total_batches = len(loader)
    start_time = time.time()

    print(
        "[RDcomm infer] start: "
        f"batches={total_batches}, max_batches={args.max_batches}, "
        f"thresholds={thresholds}"
    )

    for batch_idx, batch_data in enumerate(loader):
        if args.max_batches is not None and int(args.max_batches) >= 0:
            if batch_idx >= int(args.max_batches):
                break

        if batch_data is None:
            continue

        batch_data = to_device(batch_data, device)
        model_input = get_model_input(batch_data, stage)

        output_dict = model(model_input)

        pred_box_tensor, pred_score, gt_box_tensor = post_process_batch(
            dataset=dataset,
            batch_data=batch_data,
            output_dict=output_dict,
        )

        update_result_stat(
            result_stat=result_stat,
            pred_box_tensor=pred_box_tensor,
            pred_score=pred_score,
            gt_box_tensor=gt_box_tensor,
            thresholds=thresholds,
        )

        comm_stats = extract_comm_stats(output_dict)
        comm_stats_list.append(comm_stats)

        row = {"batch_idx": int(batch_idx)}
        row.update(comm_stats)
        comm_rows.append(row)

        if args.save_predictions:
            save_prediction_item(
                output_dir=output_dir,
                batch_idx=batch_idx,
                pred_box_tensor=pred_box_tensor,
                pred_score=pred_score,
                gt_box_tensor=gt_box_tensor,
                output_dict=output_dict,
            )

        if args.debug or batch_idx % 20 == 0:
            elapsed = time.time() - start_time
            pred_num = 0 if pred_box_tensor is None else int(pred_box_tensor.shape[0])
            gt_num = 0 if gt_box_tensor is None else int(gt_box_tensor.shape[0])

            print(
                "[RDcomm infer] "
                f"batch={batch_idx + 1}/{total_batches}, "
                f"pred={pred_num}, gt={gt_num}, "
                f"comm_KB={comm_stats.get('total_KB', comm_stats.get('comm_KB', 0.0)):.4f}, "
                f"final_ratio={comm_stats.get('final_selected_ratio', 0.0):.6f}, "
                f"time={elapsed:.1f}s"
            )

    ap_results = final_eval_results(
        result_stat=result_stat,
        output_dir=output_dir,
        global_sort_detections=bool(args.global_sort_detections),
    )

    comm_summary = aggregate_comm_stats(comm_stats_list)

    summary = {
        "ap_results": ap_results,
        "comm_summary": comm_summary,
        "thresholds": thresholds,
        "num_processed_batches": len(comm_stats_list),
        "tau_c": args.tau_c,
        "tau_mi": args.tau_mi,
        "checkpoint": args.checkpoint,
        "huffman_table": args.huffman_table,
        "hypes_yaml": args.hypes_yaml,
        "output_dir": output_dir,
    }

    save_json(summary, os.path.join(output_dir, "rdcomm_inference_summary.json"))

    # Save raw result_stat as torch because it may contain numpy-like arrays.
    torch.save(
        tensor_to_cpu(result_stat),
        os.path.join(output_dir, "result_stat.pth"),
    )

    if args.save_per_sample_csv:
        write_comm_csv(
            comm_rows,
            os.path.join(output_dir, "rdcomm_comm_per_batch.csv"),
        )

    return summary


def print_summary(summary: Mapping[str, Any]) -> None:
    print("\n[RDcomm infer] final summary")

    ap_results = summary.get("ap_results", {})
    if isinstance(ap_results, Mapping):
        for key in sorted(ap_results.keys()):
            print(f"  {key}: {float(ap_results[key]):.6f}")

    comm = summary.get("comm_summary", {})
    if isinstance(comm, Mapping):
        print("  communication:")
        for key in (
            "total_KB",
            "total_MB",
            "avg_KB_per_batch",
            "avg_MB_per_batch",
            "selected_message_KB",
            "abstract_KB",
            "avg_confidence_selected_ratio",
            "avg_final_selected_ratio",
            "avg_mi_selected_ratio_within_confidence",
            "num_messages",
            "num_batches",
        ):
            if key in comm:
                print(f"    {key}: {float(comm[key]):.6f}")

    print(f"  output_dir: {summary.get('output_dir', '')}")


# -------------------------------------------------------------------------
# Main
# -------------------------------------------------------------------------


def main() -> None:
    args = parse_args()

    set_random_seed(args.seed)

    device = get_device(no_cuda=bool(args.no_cuda))
    output_dir = resolve_output_dir(args)

    print(f"[RDcomm infer] device: {device}")
    print(f"[RDcomm infer] output_dir: {output_dir}")

    hypes = load_yaml(args)
    hypes = update_hypes_for_inference(hypes, args)

    dataset, loader = build_test_loader(args, hypes)

    model = create_model(hypes)
    model = model.to(device)

    stage = str(args.rdcomm_stage).lower()
    if stage == "inference":
        stage = "infer"

    set_model_stage(model, stage)

    load_model_checkpoint(
        model=model,
        checkpoint=args.checkpoint,
        device=device,
        strict=bool(args.strict_load),
        ignore_shape_mismatch=not bool(args.no_ignore_shape_mismatch),
    )

    load_huffman_table_if_needed(model, args.huffman_table)

    set_model_thresholds(
        model=model,
        tau_c=args.tau_c,
        tau_mi=args.tau_mi,
    )

    configure_inference_mode(
        get_core_model(model),
        freeze_all_params=True,
        verbose=True,
    )

    if args.data_parallel and torch.cuda.device_count() > 1:
        print(f"[RDcomm infer] using DataParallel on {torch.cuda.device_count()} GPUs")
        model = torch.nn.DataParallel(model)

    summary = run_inference(
        model=model,
        dataset=dataset,
        loader=loader,
        device=device,
        args=args,
        output_dir=output_dir,
    )

    print_summary(summary)
    print("[RDcomm infer] done.")


if __name__ == "__main__":
    main()